-- =============================================================================
-- Mneme 18 — daily journal. A journal page is an ordinary note with
-- note_type = 'journal' and the local day it belongs to in journal_date: one
-- per user per day (trash excluded, so a binned page can be started afresh).
-- Being its own type keeps journal pages out of the Inbox (capture-only) and
-- makes `type:journal` search / the Notes type filter work unchanged.
--   open_journal(day)  returns the day's page public_id, creating it if needed
--   calendar_month()   gains a `journal` flag per day (return type changes, so
--                      it is dropped and recreated)
-- Additive; nothing in `public` (Argus) is touched.
-- =============================================================================
begin;

alter table mneme.notes add column if not exists journal_date date;

-- widen the note_type check (its name was generated by Postgres, so find it)
do $$
declare c text;
begin
  for c in
    select conname from pg_constraint
    where conrelid = 'mneme.notes'::regclass and contype = 'c'
      and pg_get_constraintdef(oid) like '%note_type%'
  loop
    execute format('alter table mneme.notes drop constraint %I', c);
  end loop;
end $$;
alter table mneme.notes add constraint notes_note_type_check
  check (note_type in ('capture','knowledge','question','idea','meeting','reference','journal'));
alter table mneme.notes add constraint notes_journal_date_check
  check ((note_type = 'journal') = (journal_date is not null));

create unique index if not exists notes_journal_day_key
  on mneme.notes (user_id, journal_date) where journal_date is not null and deleted_at is null;

create or replace function mneme.open_journal(p_day date)
returns text
language plpgsql
set search_path = ''
as $$
declare
  v_uid   uuid := (select auth.uid());
  v_tz    text;
  v_today date;
  v_id    text;
begin
  if v_uid is null then raise exception 'not signed in' using errcode = '28000'; end if;
  select s.timezone into v_tz from mneme.settings s where s.user_id = v_uid;
  v_today := (now() at time zone coalesce(v_tz, 'UTC'))::date;
  if p_day is null or p_day > v_today + 1 then
    raise exception 'no journal for future days' using errcode = '22023';
  end if;

  insert into mneme.notes (note_type, journal_date, title)
  values ('journal', p_day, to_char(p_day, 'FMDay, FMDD FMMonth YYYY'))
  on conflict (user_id, journal_date) where journal_date is not null and deleted_at is null do nothing;

  select n.public_id into v_id from mneme.notes n
  where n.user_id = v_uid and n.journal_date = p_day and n.deleted_at is null;
  return v_id;
end
$$;

revoke all on function mneme.open_journal(date) from public, anon;
grant execute on function mneme.open_journal(date) to authenticated;

drop function if exists mneme.calendar_month(date, date);
create function mneme.calendar_month(p_from date, p_to date)
returns table (
  day date, notes integer, meetings integer,
  scheduled integer, open_tasks integer, done_tasks integer, journal boolean
)
language plpgsql
stable
set search_path = ''
as $$
declare
  v_tz text;
begin
  if p_from is null or p_to is null or p_to < p_from or p_to - p_from > 62 then
    raise exception 'calendar range must be at most 62 days' using errcode = '22023';
  end if;
  select s.timezone into v_tz from mneme.settings s where s.user_id = (select auth.uid());
  v_tz := coalesce(v_tz, 'UTC');

  return query
  with n as (
    -- journal pages are counted on their journal_date, not when they were typed
    select (x.created_at at time zone v_tz)::date as d,
           count(*)::int as notes,
           count(*) filter (where x.note_type = 'meeting')::int as meetings
    from mneme.notes x
    where x.deleted_at is null and x.journal_date is null
      and x.created_at >= (p_from::timestamp at time zone v_tz)
      and x.created_at <  ((p_to + 1)::timestamp at time zone v_tz)
    group by 1
  ), j as (
    select x.journal_date as d from mneme.notes x
    where x.deleted_at is null and x.journal_date between p_from and p_to
  ), t as (
    select x.due_date as d,
           count(*) filter (where x.status = 'open' and x.due_time is not null)::int as scheduled,
           count(*) filter (where x.status = 'open')::int as open_tasks,
           count(*) filter (where x.status = 'done')::int as done_tasks
    from mneme.tasks_active x
    where x.due_date between p_from and p_to
    group by 1
  ), days as (
    select d from n union select d from j union select d from t
  )
  select days.d,
         coalesce(n.notes, 0), coalesce(n.meetings, 0),
         coalesce(t.scheduled, 0), coalesce(t.open_tasks, 0), coalesce(t.done_tasks, 0),
         j.d is not null
  from days
  left join n on n.d = days.d
  left join j on j.d = days.d
  left join t on t.d = days.d
  order by 1;
end
$$;

revoke all on function mneme.calendar_month(date, date) from public, anon;
grant execute on function mneme.calendar_month(date, date) to authenticated;

commit;
